### ISSUE TITLE
Blurred pictures on passive TV

### ISSUE THREAD

**Issue by freewee** [gkv311/sview#100]
Hi
I talk you, months ago, about a problem when looking stereo pictures on my passive TV, and I thought it was a problem of antialiasing.
A guy from a french stereoscopic forum made a soft for viewing pictures on passive TV, and it works very well, so I try to see what was wrong with SView...and I found something!
Here are shots on my LG passive TV, and I can see that SView make a shift between right and left picture! You can see it on these examples (windows on the small hut (we call it carrelet, for fishing with big net), roof of the church).
Ubuntu 18.04
Thank you
Dominique Breton
[Shift.zip](https://github.com/gkv311/sview/files/7648211/Shift.zip)

**Comment by gkv311** [comment]
Could you also share original stereoscopic images?

Related issues: #40

**Comment by freewee** [comment]
I' m a little bit confused, from Ubuntu 18.04, I went to Windows7, and there is no problem ...
I went back to Ubuntu, alternate between shutter glasses (I can use them in Ubuntu) and row alternate mode, and now  there is no problem on the passive TV ...
Yesterday it was impossible to show some pictures to friends (blurred), I' ve been forced to go to Windows to show them correct pictures...
 I' will try to reproduce the problem, I will try on 20.04 and 21.10 (multiboot), but for now, the problem has gone away.
Sorry for that!
Dominique Breton

**Comment by freewee** [comment]
Hi
 Excuse me for this first post, I inverted 2 results from tests I made after a guy from a forum send a soft for viewing stereo pictures on a Passive TV.
But the problem for SView is still there, for me, Ubuntu 18.04, Quadro FX4800.
No problem for viewing mpo with 3D shutter glasses NVidia.
But viewing the pictures on a passive TV (LG) is not top with SView.
I tested with the mpo I send.
With StereoPhoto maker, in full screen, on the TV, I can read the small letters.
With SView, I tested with the 3 anti aliasing modes, but I can' t read the text, there are artefacts.
It was the feeling I had with pictures (I already said that to you), but with this mpo test I can confirm that!
Thank you
Dominique Breton
[texto_4kb_ondul.zip](https://github.com/gkv311/sview/files/7658953/texto_4kb_ondul.zip)

**Comment by gkv311** [comment]
Fill free to try new option "Smoothing" for Interlaced Output:
https://download.sview.ru/win/sViewSetup_v.21.12_7.exe

**Comment by freewee** [comment]
Hi
I was embarrassed to ask you this because I am a simple "consumer" of software, but this improvement is really functional and interesting for me, and others I hope! So thank you very much for this responsiveness!
And I'm waiting for an Ubuntu version !!!
Thank you very much!
Dominique Breton
