### ISSUE TITLE
WebP doesn't match PNG colors

### ISSUE THREAD

**Issue by ThreeDeeJay** [gkv311/sview#107]
Howdy.
I tried converting a PNG file to WebP Lossless but the colors are different in sView
![image](https://user-images.githubusercontent.com/71472458/170121830-a0450251-9ed8-4e67-b44b-bb7665aaf3ff.png)
![image](https://user-images.githubusercontent.com/71472458/170121864-0b7c69bc-af7d-4b9d-add8-e2fbd0a51024.png)
Notice the PNG (top) has slightly higher contrast.
However, in the browser (tried Firefox and Chromium), they look identical.
![image](https://user-images.githubusercontent.com/71472458/170122226-b265501e-8079-4c12-acd5-c6db554b6b1e.png)
Someone suggested the app might be ignoring one of the color profiles, so I figured I'd report it here.

**Comment by ThreeDeeJay** [comment]
By the way, here are the [PNG and WebP files](https://github.com/gkv311/sview/files/8765891/PNG-WebP.zip).
PNG was converted with this [tool](https://github.com/ThreeDeeJay/Lossless-Image-Batch-Converters/releases/latest).

**Comment by gkv311** [comment]
sView currently relies on `libwebp` library for decoding WebP images. This looks kind of natural, but this library has a terrible API, and color conversion issue you see is done by this library while it converts RGB WebP image into YUV420 colorspace.

I have pushed a change removing `libwebp` dependency - FFmpeg nowadays supports decoding WebP much better and without such issues - colorspace of original image is preserved when supported by sView.

**Comment by gkv311** [comment]
To be included in the next release.

**Comment by gkv311** [comment]
> Someone suggested the app might be ignoring one of the color profiles, so I figured I'd report it here.

This looks irrelevant to color profiles - files do not include non-standard profiles. And indeed, sView doesn't handle color profiles (treated as sRGB).

**Comment by gkv311** [comment]
Test build could be taken [here](https://download.sview.ru/win/sViewSetup_v.22.05_25.exe).

**Comment by ThreeDeeJay** [comment]
Woah, that was quick!
Now it works as expected so I'll go ahead and close this issue 👍
![image](https://user-images.githubusercontent.com/71472458/170138625-a43600f4-b48d-4383-a0cb-0f8dc61bb94e.png)
