### ISSUE TITLE
Use global menu bar on Mac OS

### ISSUE THREAD

**Issue by jobukkit** [gkv311/sview#109]
The Mac OS version of the app should use the system's global menu bar instead of its own menu bar that overlaps the photo.

<img width="459" alt="Schermafbeelding 2022-07-21 om 16 39 51" src="https://user-images.githubusercontent.com/2750434/180242072-29e2efe3-4d6f-4bff-8310-81ee6ede0b48.png">

**Comment by gkv311** [comment]
sView is a cross-platform application providing a uniform interface across supported platforms with help of minimalistic built-in GUI library performing OpenGL rendering. This allows to provide user interface also on stereoscopic devices that are not supported by native GUI frameworks.

There is no intent to replace or support "native" menu interfaces in sView in the future. You may try other players that follow different GUI concepts, which I believe should be a plenty on macOS platform.
