### ISSUE TITLE
feature rq: auto open two image files

### ISSUE THREAD

**Issue by tksharpless** [gkv311/sview#11]
Hi Kirill,

Sview is a great help to me in stitching stereo spheres, and developing s/w for that.  It would be even greater with what I would hope is a simple modification.  Now, when given just a list of source file names (as for example by drag-n-drop), SView opens the first one, auto-selecting video or still mode according to file type.  

Better, if given two file names, open them both, as the left and right views.  Then a simple d-n-d would be enough to start the display I need.  At present I have to use an intermediate Windows batch file, with --left=%1 --right=%2.  Not problem, but this requires some "user programming" (and the associated CLI window clutters the screen).

-- Thomas

**Comment by gkv311** [comment]
Hello Thomas,

I have the same idea a long time ago.
Two files within Drag & Drop are now handled as stereopair - this feature will be available in next release.

**Comment by tksharpless** [comment]
Thx Kirill, looking forward to the next release. -- Tom
