### ISSUE TITLE
Direct3D SoftwarePageflipping

### ISSUE THREAD

**Issue by c-a-s-m** [gkv311/sview#112]
Newer nVidia drivers does not support 3D Vision anymore. But some devices (like DLP projectors) can receive frame-packed data to display stereo images even with them.

"Shutter glasses" option allows different "Quad buffer type" to be selected.
"Direct3D (NVIDIA) Disabled" does not work with newer drivers, and it's expected.
"OpenGL Hardware" didn't work with older drivers and does not work with newer one ("OpenGL Hardware QuadBuffer is unavailable").
"OpenGL Emulated" does work with newer drivers in window mode, but a switch to full screen mode makes everything to disappear (desktop with other running applications are shown). sView continues to work, sound goes on, but nothing is displayed, there is no sView application on the task bar, and it's worth to press Esc immediately at once to quit.

From another side, Stereoscopic Player does use SoftwarePageflipping in the specified environment without major problems. apitrace shows that it uses Direct3D9 in both window and full screen modes for that.

The UI of sView is superior, sView supports subtitles easily as well. I want to continue using sView even with newer nVidia drivers.

Is there a chance that Direct3D SoftwarePageflipping (not nVidia specific) will be added to it?

**Comment by gkv311** [comment]
> "OpenGL Emulated" does work with newer drivers in window mode, but a switch to full screen mode makes everything to disappear (desktop with other running applications are shown). sView continues to work, sound goes on, but nothing is displayed, there is no sView application on the task bar, and it's worth to press Esc immediately at once to quit.

I don't see any similar issues on my system - it should be related to some problems with system / drivers. Consider reporting problem to your vendor.

> Is there a chance that Direct3D SoftwarePageflipping (not nVidia specific) will be added to it?

sView is an OpenGL-based software and there is no point in investing Direct3D output, as well as into very limited software emulation of page flipping. As long as nobody will suggest an actual contribution to the code, this will not happen.
