### ISSUE TITLE
sView switches to frame-sequential erroneously and playback is not smooth

### ISSUE THREAD

**Issue by c-a-s-m** [gkv311/sview#113]
I have several frame-sequential files and use sView in "Shutter glasses" mode (both "Direct3D (NVIDIA)" and "OpenGL Emulated") to render them. The visualization looks shivering. Pressing pause and looking at the left and right image separately seems like the images are taken from different (but close) moments. I've never seen anything like that with other file types. Probably it's not connected with seeking, viewing a file from the very beginning without a seek looks the same.

Playing the same files with Stereoscopic Player gives a usual smoothness. A left and right images in pause mode look similar.

Frame-sequential files can easily be fetched from BR3D disks without hours of recompression, and thus they can be more convenient then ordinary FullOverUnder recompressed ones. It would be nice to have a decent support of such files in sView.

**Comment by c-a-s-m** [comment]
Images from playback

![Stereoscopic Player](https://user-images.githubusercontent.com/112732556/188244247-9461ad86-df79-4488-9b01-295c79ef534f.png)
![sView](https://user-images.githubusercontent.com/112732556/188244256-f8b8cabe-039d-4cf9-be29-01f321134737.png)

**Comment by gkv311** [comment]
Frame-sequential format is quite badly defined in video codecs / containers, and as consequence has implementation issues to support playback. If you will share file sample, I would be able to at least comment what is happening.

> Frame-sequential files can easily be fetched from BR3D disks without hours of recompression,

How exactly MVC-encoded streams could be extracted into frame-sequential format nowadays? And if you have a pipeline to achieve this, then extracting video in dual-stream format, which is better supported by sView, should be even easier task.

**Comment by c-a-s-m** [comment]
The MakeMKV application makes that magic.

**Comment by gkv311** [comment]
MVC streams #68 are currently not supported / handled properly by [FFmpeg](ffmpeg.org) - so you might want to contact this project.
