### ISSUE TITLE
libStGLWidgets error on Mageia 8

### ISSUE THREAD

**Issue by jobukkit** [gkv311/sview#114]
I tried to install sView on Mageia 8, but when I click on the icon nothing happens. When starting from the terminal I get the error `sView: error while loading shared libraries: libStGLWidgets.so: cannot open shared object file: No such file or directory`

**Comment by gkv311** [comment]
Have you built sView from source code? What were your steps to build / run sView?

**Comment by jobukkit** [comment]
Yes, I installed dependencies with `dnf` and installed sView with `make` and `make install`.

**Comment by gkv311** [comment]
Sorry, I'm not familiar with Mageia. Hopefully you've been already find some support from it's other users.
