### ISSUE TITLE
[Feature Request] 2D to 3D conversion using MiDaS Machine Learning Model

### ISSUE THREAD

**Issue by ThreeDeeJay** [gkv311/sview#117]
Recently I found out there's a very promising 2D to 3D converter ([DepthViewer](https://github.com/parkchamchi/DepthViewer)) that uses machine learning ([MiDaS](https://github.com/isl-org/MiDaS)) 

> [WebGL Demo](https://parkchamchi.github.io/DepthViewer/) ([WebXR version](https://parkchamchi.github.io/DepthViewer/vr_version/))
>     [Releases](https://github.com/parkchamchi/DepthViewer/releases)
>     [Steam Page](https://store.steampowered.com/app/2218510/DepthViewer/)
>     [Play Store (Yes, you can use your $5 cardboard)](https://play.google.com/store/apps/details?id=com.parkchamchi.DepthViewer)
![mounts_100](https://user-images.githubusercontent.com/71472458/212241710-f0c3b996-9cd3-4d18-919e-987b90784fbf.jpg)
![cat_400](https://user-images.githubusercontent.com/71472458/212241714-b960d2e8-a2cf-42d5-91f9-db03019cf144.gif)

Its depth detection is pretty decent and performance when converting videos in realtime is pretty good tho it's quite shaky.
It can even mirror and convert the desktop to 3D, although there the performance is pretty poor.
The models are constantly being updated and improved, but at the moment there's only a version for VR.
So it would be cool to have an alternative for non-VR 3D displays supported by sView like 3DTVs and 3D Vision.

**Comment by gkv311** [comment]
Thanks for your suggestion.

Conceptually, sView was designed to display contents, that has been already prepared for stereoscopic displays - e.g. any 2d to 3d conversion is out of scope of project objectives.

Though, is someone would suggest a working patch with such (optional) feature, that wouldn't considerably change sView architecture, it might be considered.
