### ISSUE TITLE
Install & Upgrades with Chocolatey

### ISSUE THREAD

**Issue by TizianoMad** [gkv311/sview#119]
Hello Kirill,

I would like it a lot if sView could be updated with Chocolatey.

Chocolatey is an excellent tool which upgrades all programs installed via their server.
Every week, I just need 2 clicks to run "Choco Updates" as admin, and I have about 20 programs which are updated in one go, without needing to open any of them.

Any dev can provide their app and new packages for upgrades.
Hope you like the idea too.

https://community.chocolatey.org/packages
https://github.com/chocolatey/choco

Thank you for your work.

**Comment by gkv311** [comment]
If this requires some patches to the project - pull requests are welcome. If this is the request for some package maintainer - so far there are no users of mentioned package manager.
