### ISSUE TITLE
Bug Ubuntu 23.04 SView does not work

### ISSUE THREAD

**Issue by lexterror** [gkv311/sview#124]
Im getting an error that prevents the app from working

![Screenshot_2023-10-24_11-25-39](https://github.com/gkv311/sview/assets/16135535/45c53553-8d5a-47a6-b0a7-4f2a26ce4b8b)

**Comment by gkv311** [comment]
You haven't installed sView in system - this message comes from so-named `sview` tool  available in Ubuntu since some of it's releases.

**Comment by lexterror** [comment]
there is no release candidate for ubuntu 23.04

**Comment by lexterror** [comment]
I used the "Jammy" version. Thank you!
