### ISSUE TITLE
how to change mode between image and movie player

### ISSUE THREAD

**Issue by nicole8806** [gkv311/sview#13]
like the title, I can only use it watch the picture, and how to watch movie?

**Comment by gkv311** [comment]
sView executable starts in different modes depending on the file type passed as argument or options --in=video and --in=image.

**Comment by nicole8806** [comment]
Thanks, solved it, and the sview can play the stream data from some transmission like udp?

**Comment by gkv311** [comment]
> and the sview can play the stream data from some transmission like udp?

yes, if it is supported by FFmpeg.
