### ISSUE TITLE
Missing textures after building

### ISSUE THREAD

**Issue by Mx2uller** [gkv311/sview#133]
Hi,
I am trying to make [nix](https://nixos.org/) derivation. I built sView successfully but when running program I get following error output in terminal:
```
ERROR !! EDID from XRandr for Output #33 (DP-1) is invalid!
ERROR !! X, no Quad Buffered visual
[image2 @ 0x16f1400] Could find no file with path '' and index in the range 0-4
ERROR !! StOutPageFlip Plugin, Texture missed: AVFormat library, couldn't open image file. Error: No such file or directory
ERROR !! StFTFontRegistry, major font file 'NanumMyeongjo.ttf' does not exist!
ERROR !! StFTFontRegistry, major font file 'NanumMyeongjoBold.ttf' does not exist!
ERROR !! StFTFontRegistry, major font file 'NanumGothic.ttf' does not exist!
ERROR !! StFTFontRegistry, major font file 'NanumGothicBold.ttf' does not exist!
ERROR !! StFTFontRegistry, major font file 'DroidSansFallbackFull.ttf' does not exist!
```
sView is running, this is what GUI looks like:
![image](https://github.com/user-attachments/assets/cb8ac905-f973-4020-bbaa-2a0b1d96dd78)

Program is not installed under `/usr` but inside `/nix/store/5acabwmqy2vaf0nvbpshxpd5j1hf0s3b-sview-20_08`, so I want to know how does program gets location of GUI elements, is it some kind of environment variable or it reads some predefined path? Program is running and playing videos, GUI elements are invisible but they work.
This is directory structure:
```
/nix/store/5acabwmqy2vaf0nvbpshxpd5j1hf0s3b-sview-20_08
└── usr
    ├── bin
    ├── lib
    │   ├── firefox
    │   │   └── plugins
    │   ├── mozilla
    │   │   └── plugins
    │   └── sView
    └── share
        ├── application-registry
        ├── applications
        ├── icons
        │   └── hicolor
        │       ├── 128x128
        │       │   └── apps
        │       ├── 144x144
        │       │   └── apps
        │       ├── 16x16
        │       │   └── apps
        │       ├── 24x24
        │       │   └── apps
        │       ├── 256x256
        │       │   └── apps
        │       ├── 32x32
        │       │   └── apps
        │       ├── 48x48
        │       │   └── apps
        │       ├── 512x512
        │       │   └── apps
        │       ├── 64x64
        │       │   └── apps
        │       ├── 72x72
        │       │   └── apps
        │       ├── 96x96
        │       │   └── apps
        │       └── scalable
        │           └── apps
        ├── menu
        └── sView
            ├── demo
            ├── icons
            ├── info
            ├── lang
            │   ├── ChineseS
            │   ├── Czech
            │   ├── Deutsch
            │   ├── English
            │   ├── Español
            │   ├── français
            │   ├── Korean
            │   └── русский
            ├── shaders
            │   ├── StOutAnaglyph
            │   ├── StOutInterlace
            │   └── StOutIZ3D
            ├── textures
            └── web

58 directories
```
Note: I am not developer but I like your program and want to make this derivation so it is available on nix.

**Comment by gkv311** [comment]
If you are installing sView system-wise, but not into `/usr`, then you might want to configure `APP_PREFIX` variable for `make` sView like the [following recipe](https://github.com/flathub/ru.sview.sView) for flathub:
```
make APP_PREFIX=/app DISABLE_UPDATER=1
make install APP_PREFIX=/app
```

But I guess that the path is something randomly generated in your case. sView looks for resources in the following order:
- `$StShare` environment variable (the folder that contains `textures`, `shaders`, `icons` subdirectories);
- Relative to the location of sView executable (best option for portable builds and development, see layout below);
- Predefined system path (`APP_PREFIX"/share/sView/"` on Linux, e.g. `/usr/share/sView/` by default).

```
└── sViewPortable
    ├── icons
    ├── info
    ├── lang
    │   ├── ChineseS
    │   ├── Czech
    │   ├── Deutsch
    │   ├── English
    │   ├── Español
    │   ├── français
    │   ├── Korean
    │   └── русский
    ├── shaders
    │   ├── StOutAnaglyph
    │   ├── StOutInterlace
    │   └── StOutIZ3D
    ├── textures
    └── web
```

**Comment by Mx2uller** [comment]
Hi,
I did it like you said and configured `APP_PREFIX` and `$StShare` variable. GUI elements are now visible, before configuring `APP_PREFIX` I had to use `patchelf` to add path to lib directory to `rpath`. Now sView detects them automatically. Only issue now are missing fonts. I checked flathub repo and it looks like fonts are copied to APP_PREFIX/share/fonts. Is that only way to make fonts visible to sView?

Missing text in Language sub menu:
![image](https://github.com/user-attachments/assets/f1661237-5d10-44ff-8c55-20de641feb47)

**Comment by gkv311** [comment]
sView is not shipped with any fonts on it's own - application tries to use fonts, installed in the system.

On Linux/Unix systems (save the Android and macOS), it relies on [fontconfig](https://fontconfig.pages.freedesktop.org/fontconfig/fontconfig-user.html) library to find the fonts. sView also looks into `"/usr/share/fonts"` and `"/usr/local/share/fonts"` as last resort. Don't know if *fontconfig* could be configured to look onto extra folders via `.fonts.conf` locally, or sView modification will be necessary (the logic could be found in `StShared/StFTFontRegistry.cpp`).

In your case, sView cannot find any known font for Chinese and Korean symbols - e.g. one from:
```
    // korean
    myFilesMajor.add(stCString("NanumMyeongjo.ttf"));
    myFilesMajor.add(stCString("NanumMyeongjoBold.ttf"));
    myFilesMajor.add(stCString("NanumGothic.ttf"));
    myFilesMajor.add(stCString("NanumGothicBold.ttf"));
    myFilesMinor.add(stCString("NotoSerifCJK-Regular.ttc"));

    // chinese
    //myFilesMajor.add(stCString("DroidSansJapanese.ttf"));
    myFilesMajor.add(stCString("DroidSansFallbackFull.ttf"));
```

**Comment by Mx2uller** [comment]
Hi,
everything works now, I made `.font.conf` and added paths to `nanum` and `DroidSans` fonts. Tank you for help.
