### ISSUE TITLE
open it with oculus?

### ISSUE THREAD

**Issue by HazemSamir** [gkv311/sview#14]
I chose the Oculus Rift from devices list and I am connecting Oculus to my pc, but no thing happened. I am wondering if there are more steps to do? as I can not find in the user manual any thing about Oculus.

**Comment by gkv311** [comment]
Are you using "sView for Oculus Rift (preview)"?

**Comment by HazemSamir** [comment]
Do you mean from this menu or another software?
![sview_oculus](https://cloud.githubusercontent.com/assets/12578145/17317501/01ad230c-5887-11e6-8d0b-58ba21132477.png)

**Comment by gkv311** [comment]
No, I meant the sView version build with Oculus Rift SDK on sview.ru
The main sView release is not based on Oculus Rift SDK and will work only when HMD is connected as dedicated display in system ("old" way which Oculus has disabled at some moment).

**Comment by HazemSamir** [comment]
Sorry I did not see it when I downloaded the player. However, I tried it now and it gives me this message:

>"StOutDistorted, Oculus rift is not connected" 

Although it's connected and is working when I launch the Oculus Home app. I tried allowing unknown sources from Oculus Home app but in vain. Sorry bothering you again!

**Comment by gkv311** [comment]
Sorry, I don't know what has been changed since Oculus Rift release.
Some users have been able to launch sView somehow - have no idea what they have been changed in driver settings. Maybe something has been changed since that.

**Comment by HazemSamir** [comment]
Well thanks a lot, I will keep trying and I will update if I found a solution.

**Comment by HazemSamir** [comment]
It's really the coolest and most stable open source player for 360 videos I found till now. I am working on [360 video projections](https://github.com/HazemSamir/transform) and I would like to extend your player to test other projections like [offset_cubemap](https://github.com/HazemSamir/transform/wiki/Offset-cube-map) which I believe it will be similar to cubemap. However, the project is too large! and I don't know from where I should start. So If you can recommend starting from certain classes or so, I will appreciate that.
thanks again

**Comment by gkv311** [comment]
sView is not so large (well, relatively to other projects and players).
Tell me where you would like to start (which functionality) - and I'll try provide some introduction.

**Comment by HazemSamir** [comment]
Well it's large for me :smile: (I am still an undergraduate student)

I would like to understand the part where a cubemap video frame is rendered,  how you extract cube faces?

**Comment by gkv311** [comment]
Cubemap texture is rendered using GLSL program (search "cubemap" in StGLWidgets/StGLImageProgram.cpp), which is managed by Image Region widget (StGLWidgets/StGLImageRegion.cpp) - e.g. camera rotation and so on (the image region is logically a widget covering entire window and drawn in background of all other widgets for GUI).

The data itself is transferred via chain:
- [Data Source StImageViewer or StMoviePlayer]
->create StImage (pointer to the image data)
->StImage is pushed into StGLTextureQueue::push() (queue of decoded frames - up to 16 for video) and creates StGLTextureData from it (image data placeholder in the queue / queue node).
-> StGLTextureData processes input image data and splits stereo pair if needed.
-> StGLImageRegion fetches new image frame from the queue StGLTextureQueue::stglUpdateStTextures()
-> StGLTextureData::fillTexture() uploads image data from CPU memory onto GPU memory as texture StGLQuadTexture / StGLFrameTextures / StGLTexture; several textures might be affected. E.g. 3 planes of YUV420p data are uploaded into 3 textures; and each eye view keeps own texture set. Cubemap texture is created here using dedicated OpenGL format (spherical panoramas are loaded as normal 2D plane textures).
-> StGLImageRegion draws new image texture.

**Comment by gkv311** [comment]
sView 17.01 now supports OpenVR library for HMD output.
It has been tested on HTC Vive, but I suppose that it should work on Oculus Rift as well - you can try.
