### ISSUE TITLE
How to use invokeAction and webuiCmdPort?

### ISSUE THREAD

**Issue by arm2arm** [gkv311/sview#16]
Hi,
I did not find any description to invokeAction. Could you please give a detail description on invokeAction and webuiCmdPort options?

**Comment by gkv311** [comment]
The following discussion might be useful:
https://github.com/gkv311/sview/issues/10

**Comment by arm2arm** [comment]
follow to your explanation I just testing it on win 7 , the server is not started:
`C:\Program Files\sView\amd64\sView.exe  --webuiCmdPort=8080 --last`

then in the second terminal 
`C:\Program Files\sView\amd64\sView.exe  --webuiCmdPort=8080 --invokeAction=quit`
But nothing happened.

**Comment by gkv311** [comment]
There is a bug in current version - the web server is actually not started since it is disabled by default, so you have to select "Web UI:8080 -> Launch once" in user interface, which does not make much sense for starting remove control without interaction...

**Comment by arm2arm** [comment]
I will keep this open until the cli bug is fixed:)

**Comment by gkv311** [comment]
The issue should be fixed now - it will be available within next release.
