### ISSUE TITLE
Is it possible to use android device as a remote controller to the sView player?

### ISSUE THREAD

**Issue by arm2arm** [gkv311/sview#17]
Is it possible to use android device as a remote controller to the sView player?

**Comment by gkv311** [comment]
You can start Web-UI in sView on desktop and access it through web-browser on Android device if them are connected to the same network.

**Comment by arm2arm** [comment]
Could you please send a reference to documentation?

**Comment by arm2arm** [comment]
nice working like a charm: on GUI: sView --in=video then selecting Media->WebUI->Launch every time
later from remote machine one can connect to 3dhostIP:8080/ and controll the playback.
