### ISSUE TITLE
Ignores rotation flag in Apple's *.mov format, leaving videos taken from iPhone upside down

### ISSUE THREAD

**Issue by jleaders** [gkv311/sview#22]
Just like images, movies can also have metadata that specifies the orientation. This flag seems to be ignored entirely by sView such that movies play upside down. In Windows Movie player however it plays right-side up. I've attached a test movie.
[IMG_6258.zip](https://github.com/gkv311/sview/files/794455/IMG_6258.zip)

**Comment by gkv311** [comment]
The patch has been pushed to master branch.
