### ISSUE TITLE
Криво склеивается картинка

### ISSUE THREAD

**Issue by HraD** [gkv311/sview#24]
Я обладатель телефона с 3D экраном PPTV King 7S (http://4pda.ru/forum/index.php?showtopic=770493)
sView stereoscopic viewer работает, изображение в 3Д (Column interlaced + исходный формат видео), но кадр как будто криво склеен из 3-х частей. Нельзя ли как то это починить?

![screenshot_2017-04-07-18-53-14](https://cloud.githubusercontent.com/assets/14878643/24809106/20f1946a-1bc7-11e7-9bd9-6b1689bda360.png)

**Comment by gkv311** [comment]
Я уже встречался с подобной проблемой на другом устройстве.
Причиной, предположительно, является некорректная работа OpenGL ES драйвера на устройстве (излишняя оптимизация?) или какое-то аппаратное ограничение GPU (что несколько удивительно для современного железа).
Тогда проблему (недостаточной точности переменной, считающей отступ пикселя от края экрана) получилось частично обойти с помощью дополнительного смещения в GLSL коде, в котором нет необходимости на других устройствах и на десктопе.

Для начала, желательно сделать скриншот с System Info - системная информация выводится в конце диалога О программе (About...).

Далее можно будет попробовать сделать несколько сборок sView и посмотреть будут ли влиять изменения в GLSL коде на вывод картинки.

**Comment by HraD** [comment]
![screenshot_2017-04-10-21-54-25](https://cloud.githubusercontent.com/assets/14878643/24878284/2f563102-1e3b-11e7-89ed-16f7b14e258f.png)
Скриншот сделал, тестить готов )

**Comment by gkv311** [comment]
> PowerVR Rouge G6200
Ну хотя бы другой производитель ;), прошлая проблема была на Mali-450 MP4.

**Comment by gkv311** [comment]
Вот сборка с ревертированными изменениями:
https://drive.google.com/file/d/0B-lkr5zq2JtEM0x2UTA3eTRkeDQ/view?usp=sharing

Перед установкой надо удалить sView установленную через Google Play.
Для проверки разницы - надо сделать аналогичный скриншот в стерео и прикрепить к данному багу.

**Comment by HraD** [comment]
Падает при запуске
![screenshot_2017-04-11-22-22-55](https://cloud.githubusercontent.com/assets/14878643/24927022/370f43d6-1f06-11e7-901c-647566638022.png)

**Comment by gkv311** [comment]
https://drive.google.com/file/d/0B-lkr5zq2JtEekhubXRmU0Z4VUU/view?usp=sharing

**Comment by HraD** [comment]
То же самое пока что
![screenshot_2017-04-12-07-40-12](https://cloud.githubusercontent.com/assets/14878643/24941829/e7ab2e04-1f55-11e7-88a6-2c186391f7d3.png)

**Comment by gkv311** [comment]
Вот новая сборка:
https://drive.google.com/file/d/0B-lkr5zq2JtEaGxoc2JTbDUxVGs/view?usp=sharing

В настройках должна появиться новая опция "Использовать текстуру-маску (совместимость)" - можно попробовать её включать/выключать, чтобы проверить есть ли разница.

**Comment by HraD** [comment]
Новая опция помогла.
С ней:
![screenshot_2017-04-12-23-53-32](https://cloud.githubusercontent.com/assets/14878643/24979172/ebd3427e-1fdb-11e7-8c71-666a9a58c49f.png)
Без нее:
![screenshot_2017-04-12-23-54-13](https://cloud.githubusercontent.com/assets/14878643/24979183/f5e332f6-1fdb-11e7-9727-c5a8280602d6.png)

**Comment by gkv311** [comment]
Обновление отправлено на Google Play.
