### ISSUE TITLE
Missing video framerate and sound bitrate

### ISSUE THREAD

**Issue by H0nzik1** [gkv311/sview#29]
I am missing video framerate and sound bitrate like in VLC player .
![ice_screenshot_20170503-175101](https://cloud.githubusercontent.com/assets/28353840/25669276/556aacba-3029-11e7-8ed7-ed148061e6b5.png)
Could you add support for this? Can you make info page show everything including audio, not just video?

**Comment by gkv311** [comment]
![sview_stream_info](https://cloud.githubusercontent.com/assets/851453/26523146/fe1638ea-4319-11e7-95e5-c229231dee6e.png)
File information has been extended by low-level numbers (as printed by ffmpeg console tool) with commit 72d7f586cf1016a290719b26aeba2f569940ec9a.
