### ISSUE TITLE
Enable 'Emulated Quad Buffer' by default when no hardware is available 

### ISSUE THREAD

**Issue by rpseng** [gkv311/sview#3]
Fist of all, thanks a lot for this very nice software!

I had sView installed some time ago and sadly overlooked the 'Emulated Quad Buffer' option, because it is under extra options. For me this option works very reliably with an Intel GPU!

While every other software produce some artifacts like flickering or tearing, sView is very smooth under emulated quad buffer. I'm using sView with a LG DLP-3D projector with generic DLP glasses under Ubuntu Linux, result is fantastic.

All the best.

**Comment by gkv311** [comment]
>Then maybe you could replace the 'no hardware available' message by another one 

The error message has been extended with suggestions.

> StShared/stAV.cpp:443:74: error: ‘av_get_channel_layout_string’ was not declared in this scope

compatibility with LibAV has been improved.
