### ISSUE TITLE
unexpected image size for cubemap

### ISSUE THREAD

**Issue by troyhome** [gkv311/sview#31]
I loaded an image 6000x1000 pixels. How is this not 6:1? 
![unexpected dims](https://user-images.githubusercontent.com/29691130/27517399-eba2b292-5999-11e7-96e1-ad3e71356bad.JPG)

**Comment by gkv311** [comment]
You have selected SideBySide stereo input + Cubemap, which would require input having 12x1 ratio.

**Comment by troyhome** [comment]
Oh thanks! I'm not even sure how to change that.

**Comment by gkv311** [comment]
You have already did that (default is Autodetection/Source) ;).
Click on the icon with L/R letters to select another format.

**Comment by troyhome** [comment]
I'm confused... I selected view>reset. The only thing I selected was Cubemap. Regardless, i made a 12x1 ratio image and still have the same issue? I'm not sure what I'm missing here. 
![more unexpected dims](https://user-images.githubusercontent.com/29691130/27517623-8f02d63a-599d-11e7-864b-92db3d595af1.JPG)
thanks for your help

**Comment by troyhome** [comment]
I think I figured it out... you have to switch to RL or LR view for 12:1? Still not sure how 6:1 works though

**Comment by troyhome** [comment]
aha! i switch to mono! Thanks!
