### ISSUE TITLE
s3DV format to Unity3d?

### ISSUE THREAD

**Issue by RYG81** [gkv311/sview#32]
Hi,

I am trying to play video on glasses free 3D Tab and found latest player works with s3DV format. Can you please help me on providing more details on this format. Or how this can be achieved in game engine shader, like Unity 3D?

Rahul

**Comment by gkv311** [comment]
Could you please share what tablet you are using?

Concerning 3D initialization - sView generates stereopair in side-by-side format (fullscreen) and asks device show it on the screen. You can check how StS3dvSurface is used within StActivity - unfortunately, initialization should be done at Java level:
https://github.com/gkv311/sview/blob/master/sview/src/com/sview/StS3dvSurface.java
https://github.com/gkv311/sview/blob/master/sview/src/com/sview/StActivity.java

StS3dvSurface is a wrapper over library which should be installed on the device itself, hence manifest file should indicate its (optional) usage:
` <uses-library android:name="com.s3dv.s3dvsurface" android:required="false" />`
https://github.com/gkv311/sview/blob/master/sview/AndroidManifest.xml

**Comment by RYG81** [comment]
[8 inch 1280 X 800 3D Tab - SY3DPC8-B.pdf](https://github.com/gkv311/sview/files/1211499/8.inch.1280.X.800.3D.Tab.-.SY3DPC8-B.pdf)
I have this 3D Tablet. Actually I want to know how you enables s3DV mode and what file is checked and accessed from system side.

Rahul

**Comment by gkv311** [comment]
> Actually I want to know how you enables s3DV mode
This is exactly what I have written within my previous reply.

**Comment by RYG81** [comment]
Sorry, I did not get what you mean. Can you please give little more detail?
Have you ever worked with Unity 3D?
Rahul

**Comment by gkv311** [comment]
No, I'm not familiar with Unity 3D.

**Comment by RYG81** [comment]
OK. Thanks.

**Comment by RYG81** [comment]
Sorry for opening it again. But can you direct me to the Open GL ES rendering part in your code?
Which file I should look in to for this

**Comment by gkv311** [comment]
Could you please be more precise?
There are a lot of OpenGL rendering code in sView - most of it in StGLWidgets library (actual rendering) and in StOutAnaglyph/StOutDistorted/StOutDual/StOutIZ3D/StOutInterlace/StOutPageFlip (preparing buffers for rendering and processing output for specific 3D device).

**Comment by RYG81** [comment]
OK. I try to describe what I actually trying to do than may be you can say possible or not possible.
I have two render texture generated in unity3D (combined to Top-Bottom or Side-By-Side format). You can count it like a image/video as input. Now I just want to have a Open GL ES side code to take this image and present it to view and make it s3DV mode ready. At same time I will initialize the 3D mode through java by making a plugin to work with unity3d.
May be I have to create a native plugin based on your C/C++ code to exchange image data with unity.
Rahul

**Comment by gkv311** [comment]
The key point of s3DV is that it is irrelevant to OpenGL ES.

You need to present side-by-side stereo pair onto Android Surface (this unity3D will automatically do for you, I suppose, if you can render side-by-side pair fullscreen) and indicate through s3DV in which stereoscopic format this surface is (see the links within the first answer - there is actually not much code).

For this you need to pick up how to control Android Surface creating routines on Java level (e.g. to find out how to override/extend Unity3D code for initialization of Android Activity / Surface). The main problem might be that there might be no way to do this with Unity3D (I don't know, but, for example, doing this with Qt/QML is certainly problematic / not possible without modifying Qt itself).

**Comment by RYG81** [comment]
OK. Will see at one more time. Keeping this post open for two days. Will close it if I don't get my thing working as it will be wasting of your time.
