### ISSUE TITLE
Projection issues with stereo 180&deg; panoramas

### ISSUE THREAD

**Issue by niveuseverto** [gkv311/sview#33]
Greetings, There is projection issue with stereo 180&deg; panoramic videos.

Dirty hack - is to recode with "fake" other hemisphere.
Checked code and didn't manage to find where sphere projection is taking it own business.

If you point me there, I'll try to make pr.

**Comment by gkv311** [comment]
There is no support for 180 degrees panoramas, only for 360 degrees.
StGLWidgets/StGLImageRegion.cpp manages image rendering, and there is also StPanorama enumeration (include/StImage/StImage.h) which is used in several places to define which panorama type is in the frame.

**Comment by niveuseverto** [comment]
Thank you, Will try to implement 180&deg; logic.

**Comment by niveuseverto** [comment]
Here WIP variant: #34

**Comment by gkv311** [comment]
Hemisphere projection mode has been implemented by 1e5af2d5c15302efb07ba29d18e3daca7c820dfb
Please re-open / create new issue in case if it does not work as expected.
