### ISSUE TITLE
Panoramic photo

### ISSUE THREAD

**Issue by lavAzza2** [gkv311/sview#35]
Hello.
On  some PC panoramic photo looks like this:

![photo5219817061163837557](https://user-images.githubusercontent.com/19432725/36472025-41b486a2-1712-11e8-90b8-cf9ac93a8ecc.jpg)
![photo5219817061163837558](https://user-images.githubusercontent.com/19432725/36472024-417ef1e0-1712-11e8-8e6e-3a1d12260a7a.jpg)

On another PC the same photo looks ok.
I tryed 2 PC with Intel Graphics 630 with latest drivers, booth of them has this bug.

**Comment by gkv311** [comment]
Closed as not enough info to reproduce issue.
