### ISSUE TITLE
Is it possible

### ISSUE THREAD

**Issue by DTNql242** [gkv311/sview#36]
Is it possible that there is a light version of sview when I download the programm? I searched an updated alternative to the stereoscopic player, and sview seems to be a picture and movie player for 3D formats. After installation on my System (Win7) I can only open pictures. There is no menu for movies. It seems to be a light version that is different to the function the programm should have. Or what is wrong?

**Comment by gkv311** [comment]
The last releases (for a while) always install both Image Viewer and Movie Player. There are, however, Checkboxes for file associations.
Try reinstalling the application anew

**Comment by DTNql242** [comment]
I did it several time. When I start the program, there opens a windows "demo.jps - sview" with the 3D-picture. In the menu top left there are the menues:
Medien - Bild öffnen Eine / Zwei Dateien, Bild speichern als, Quelle Stereoformat, Bildinfo, beenden. Es ist nicht möglich, Videos zu öffnen, auch nicht indem man sie auf das Programm zieht, dann kommt die Fehlermeldung "Cannot load image file .... input file is not an image". Because I never saw this software functionally, I don´t know how it should look. I also checked the file associations, it doesn´t change anything. In menu "Help" "About" sview ...17.10...Image viewer allows to open images in formats jpeg, png, mpo... there is no video! This programm is only a picture viewer. But why is there a description on the homepage that the program plays video? The "sViewSetup_v.17.10_23" from your homepage installs a picture-viewer. Strange!

**Comment by gkv311** [comment]
Check start menu - there should be dedicated items for Image Viewer and Movie Player

**Comment by DTNql242** [comment]
I´m sorry there is no item for Movie Player. Are the Movie Player and the Image Viewer two different programs? Then it seems like when I start sview it goes directly to the image viewer without a choice. If it is one program for both, the menue item is missing on my installation. Is it possible to download an older version of the software to try it? Thanks for your answers, I really despair.

**Comment by gkv311** [comment]
Could you share a screenshot with your start menu and sView folder there?

**Comment by DTNql242** [comment]
I got it! I NEVER work with start menu. In your last answer was the solution, but I expected you meant the start menu of Sview not the start menu of windows. Sview made only one desktop shortcut which is the image viewer. In the folder of sview there is onle one .exe which is the image viewer, too. The movie player is a standalone program which can be found in sview/amd64. The answer is: sview contains of two standalone programs, one is for images and one for movies. The one for movies is hidden in a subfolder called amd64. This is what I didn´t expected. Thank you for your reply, I will test your programm now and I hope it plays what I want to view.

**Comment by DTNql242** [comment]
Great program! It runs all VR 3D Movies and my selfmade ones, too. Because of pan/scan and parallaxe control it is much better than KMPlayer. And it opens much faster. Seems I finally found a worthy replacement of my good old stereoscopic player. Thank you.

**Comment by gkv311** [comment]
> The movie player is a standalone program which can be found in sview/amd64.

Nope, it is not like this. sView.exe is for both - Image Viewer and Movie Player, they are just started depending on passed file name or arguments.
amd64 is for 64-bit binaries, which are used by default (32-bit is preserved for compatibility with old 32-bit Browsers).

>  Sview made only one desktop shortcut which is the image viewer.

Well, I don't use Desktop links. Indeed, it seems that installer creates only one link on Desktop.

**Comment by DTNql242** [comment]
Start Menu:
"C:\Program Files\sView\amd64\sView.exe" --in=video
"C:\Program Files\sView\amd64\sView.exe" --in=image --demo="C:\Program Files\sView\demo.jps"

I need calling parameters to start the program in the right way? Why that? I want to start a programm, open and chose whatever movie or image on the same surface and of course I don´t want to give all extensions to Sview (avi, mkv) I use other players for non 3D-Movies and non 3D-Images.
Again something I didn´t expected. No other program on my system works like that.
 
In the end, the movie player works great for me. I made a shortcut to my desktop. I like the desktop, it is more easy to sort than the folders and subfolders in start menu. A matter of taste.

**Comment by arm2arm** [comment]
hi,
you can simply use two shortcuts one is as the video player and another for
the images.
actually the command line options are one of the major functions used in
our 3d system. its an excellent future which is missing in most of the
players.
a.


DTNql242 <notifications@github.com> schrieb am Mi., 28. März 2018, 08:25:

**Comment by gkv311** [comment]
sView comes with two dedicated applications - Media Player and Image Viewer.
This was intended design choice (an interface is adopted per usage scenario), but also has modular architecture legacy - initially sview.exe loaded modules/plugins dynamically, and it was even possible excluding Image Viewer or Media Player from installation.

Nowadays, support of dynamically loaded plugins has been dropped as unused, and sview.exe is aware of both applications. I think, it would be useful adjusting an interface to have shortcuts between Image Viewer / Media Player - this feature will be added to planning.
