### ISSUE TITLE
Not Working after Upgrade Ubuntu 18.04

### ISSUE THREAD

**Issue by freewee** [gkv311/sview#38]
sView working with W7 W10 Ubuntu 16.04 LTS
After Ubuntu 18.04 Upgrade, clicking the icon says error when opening the application, Nothing happens.
I try to uninstall and reinstall without changing the behavior.

Am I alone for this? What can I try ??

Thank you

**Comment by gkv311** [comment]
I have found that Ubuntu has package with the same name (but completely another application), so that after upgrade wrong package is selected by apt, in case if you are using Launchpad. I haven't yet solved this issue - the proper solution would be renaming package, but this would be awkward. So maybe I'll just play with version numbers to make my package preferred.

**Comment by rommulo9** [comment]
> sView working with W7 W10 Ubuntu 16.04 LTS
> After Ubuntu 18.04 Upgrade, clicking the icon says error when opening the application, Nothing happens.
> I try to uninstall and reinstall without changing the behavior.
> 
> Am I alone for this? What can I try ??
> 
> Thank you

I came across exactly the same problem when upgrading my KDE Neon to the base of Ubuntu 18.04.
I hope this will soon resolve, because I consider sView the best cross-platform 3D image viewer!

**Comment by gkv311** [comment]
```
kirill@kirill-xubu:~$ apt-cache show sview
Package: sview
Architecture: amd64
Version: 17.11.2-1build1
Priority: extra
Section: universe/admin
Source: slurm-llnl
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Gennaro Oliva <oliva.g@na.icar.cnr.it>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 456
Depends: libc6 (>= 2.4), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.31.8), libgtk2.0-0 (>= 2.14.0), libslurmdb32 (>= 14.11.0), slurm-client (= 17.11.2-1build1)
Filename: pool/universe/s/slurm-llnl/sview_17.11.2-1build1_amd64.deb
Size: 133392
MD5sum: b008c153502ecac739390315e5c574eb
SHA1: ebf5ea50601375f74c9a1a88ae3102e58483dd92
SHA256: ae786e97724bcaf48d4b4c7d300bcde92f9dd4c2693fbd0394b2a0ef2a7b0a8b
Homepage: http://slurm.schedmd.com
Description-en: GUI to view and modify SLURM state
 SLURM, the Simple Linux Utility for Resource Management,
 is an open-source cluster resource management and job scheduling.
 This package contains sview a GUI that can be used to view SLURM
 configuration, job, step, node and partitions state information.
 Authorized users can also modify select information.
Description-md5: a9a68fd20cd1b622593baf4197ab5993

Package: sview
Priority: extra
Section: video
Installed-Size: 12218
Maintainer: Kirill Gavrilov <kirill@sview.ru>
Architecture: amd64
Version: 17.10-2~bionic
Depends: libavcodec57 (>= 7:3.4.2) | libavcodec-extra57 (>= 7:3.4.2), libavformat57 (>= 7:3.4.2), libavutil55 (>= 7:3.4.2), libc6 (>= 2.17), libconfig++9v5 (>= 1.5-0.4~), libfreetype6 (>= 2.2.1), libgcc1 (>= 1:3.0), libgl1-mesa-glx (>= 7.7), libglib2.0-0 (>= 2.12.0), libgtk2.0-0 (>= 2.8.0), libopenal1 (>= 1.14), libstdc++6 (>= 5.2), libswscale4 (>= 7:3.4.2), libx11-6, libxpm4, libxrandr2 (>= 2:1.2.99.2), xdg-utils
Filename: pool/main/s/sview/sview_17.10-2~bionic_amd64.deb
Size: 7407280
MD5sum: b1d272b645231515207f1baee4fbbdd0
SHA1: cbb6f331556251e0d8aa4114052f04b026995c4f
SHA256: 3411e562b9a15da789481b7a7342e973625a4287f6f42b5b9eb26a6e0c60548e
Description-en: stereoscopic media player sView
 .
 sView is a stereoscopic Image Viewer and Movie Player.
 Requires OpenGL2.0+ for rendering and OpenAL for sound output.
Description-md5: c4e09fa06fa037b832f6ed31c275dc65
```

**Comment by gkv311** [comment]
Package with epoch=1 has been uploaded to PPA for bionic (Ubuntu 18.04) to workaround name collision (package can be renamed in future to properly solve the problem).

Try updating / reinstalling sView from PPA.
https://launchpad.net/~sview/+archive/ubuntu/stable

**Comment by freewee** [comment]
Thank you, that' s working for me !
Dominique
