### ISSUE TITLE
Windows 10  "not rated by NVidia"

### ISSUE THREAD

**Issue by freewee** [gkv311/sview#39]
Hi

I' m using sView in W7 W10 Ubuntu 64b.
In W10;, I get the classical "application not rated by NVidia" message, disappearing with the classical Ctrl-Alt-Inser, but the message reappear after each reboot of sView...
Is there something to do???
Thank you very much for this great application!

Dominique Breton

**Comment by gkv311** [comment]
As you may deduce from the message "This application is not rated by NVIDIA" it is coming from NVIDIA driver and application is not supposed (and unable) to do anything with it:
> This is our policy at NVIDIA that we always show it the first time you run it for every game with a profile.
> We do this so you instantly know what rating a particular game has.

https://forums.geforce.com/default/topic/488718/disable-34-this-application-is-not-rated-34-in-the-application-3d-vision-programming/

You make look on NVIDIA forums or contact NVIDIA support in case if it doesn't work as expected.
