### ISSUE TITLE
Поддержка arm

### ISSUE THREAD

**Issue by malehovich** [gkv311/sview#43]
Поддерживает ли плеер устройства на платформе arm ? При компиляции g+ ругается на параметры sse и mmx ? Спасибо.

**Comment by gkv311** [comment]
ARM устройства поддерживаются на платформе Android.
Прочие Linux/macOS предполагаются x86 по-умолчанию - для сборки под ARM понадобиться поправить Makefile (конфигурационных скриптов для генерации Makefile на данный момент не предусмотрено).

**Comment by malehovich** [comment]
А не подскажете есть ли смысл замарачиваться ? Потянет ли arm pageflipping?

**Comment by gkv311** [comment]
Pageflipping как таковой предполагает наличие специальной поддержки со стороны OpenGL драйвера (Quad Buffer) - при наличие таковой производительность устройства не должна быть критичной для корретной работы затворных очков. Однако я не слышал о таких устройстовах на ARM.

Если же говорить о программном Pageflip, суть которого в непрервыном чередовании левого и правого кадра стандартными средсвами OpenGL, то надёжность такого метода оставляет желать лучшего и зависит от множества факторов, которые трудно отследить и повлиять. Самый первый барьер - скорость отрсовки одного кадра должна быть достаточно быстрой (желательно с некоторым запасом).

Мне неизвестны случаи использования программного Pageflip не на десктопных x86 системах, поэтому трудно предсказать, сможет ли он заработать как таковой (как и то, можно ли сейчас найти такие затворные очки и монитор, которые можно активировать без дополнительной драйверной поддержки). Но чисто теоретически, хорошая SoC на ARM вполне может оказаться достаточно производительной, по крайней мере для базового применения (монитор с не повышенным разрешением, статические картинки не высокого разрешения; для воспроизведения видео конфигурация малопригодна даже на производительном x86).

**Comment by malehovich** [comment]
У меня плата jetson tk1 и проектор с поддержкой 3d dlp. Nvidia пишет что чип поддерживает OpenGL 3.1. Раньше для проектора использовал x86 и stereoscopic. Но программный pageflip в нем работает ужасно...

**Comment by malehovich** [comment]
compilation errror (((

/home/ubuntu/sview/include/stTypes.h: In function ‘void* stMemAllocAligned(const size_t&, const size_t&)’:
/home/ubuntu/sview/include/stTypes.h:404:43: error: ‘_mm_malloc’ was not declared in this scope
     return _mm_malloc(theNbBytes, theAlign);
                                           ^
/home/ubuntu/sview/include/stTypes.h: In function ‘void stMemFreeAligned(void*)’:
/home/ubuntu/sview/include/stTypes.h:440:27: error: ‘_mm_free’ was not declared in this scope
     _mm_free(thePtrAligned);
                           ^
make: *** [/home/ubuntu/sview/StShared/StAVFrame.o] Error 1

**Comment by gkv311** [comment]
Попробуйте с последним обновлением из master
(коммит " stMemAllocAligned - use posix_memalign instead of _mm_malloc for non-x86 target")

**Comment by malehovich** [comment]
теперь вот такое (((

/home/ubuntu/sview-master/StMoviePlayer/StVideo/StVideoQueue.cpp: In member function ‘void StVideoQueue::decodeLoop()’:
/home/ubuntu/sview-master/StMoviePlayer/StVideo/StVideoQueue.cpp:870:13: error: ‘AVFrameSideData’ was not declared in this scope
             AVFrameSideData* aSideDataSync = av_frame_get_side_data(myFrame.Frame, (AVFrameSideDataType )1000);
             ^
/home/ubuntu/sview-master/StMoviePlayer/StVideo/StVideoQueue.cpp:870:30: error: ‘aSideDataSync’ was not declared in this scope
             AVFrameSideData* aSideDataSync = av_frame_get_side_data(myFrame.Frame, (AVFrameSideDataType )1000);
                              ^
/home/ubuntu/sview-master/StMoviePlayer/StVideo/StVideoQueue.cpp:870:85: error: ‘AVFrameSideDataType’ was not declared in this scope
             AVFrameSideData* aSideDataSync = av_frame_get_side_data(myFrame.Frame, (AVFrameSideDataType )1000);
                                                                                     ^
/home/ubuntu/sview-master/StMoviePlayer/StVideo/StVideoQueue.cpp:870:110: error: ‘av_frame_get_side_data’ was not declared in this scope
             AVFrameSideData* aSideDataSync = av_frame_get_side_data(myFrame.Frame, (AVFrameSideDataType )1000);
                                                                                                              ^
make: *** [/home/ubuntu/sview-master/StMoviePlayer/StVideo/StVideoQueue.o] Error 1

**Comment by gkv311** [comment]
Что за версия Ubuntu (и библиотеки FFmpeg, если она не из репозитария) используется?

**Comment by malehovich** [comment]
а вот про ffmpeg то я и забыл )) ubuntu 14.04 - только такая есть родная для этой платы... аппаратной поддержки в ffmpeg нет ((( поэтому наверное нет смысла и дальше разбираться.. спасибо за ответы !

**Comment by gkv311** [comment]
Ubuntu 14.04 достаточно старый релиз.

На Launchpad последний релиз sView для Ubuntu 14.04 Trusty Tahr был в конце 2015 года.
Launchpad является "фильтром" списка поддерживаемых версий Ubuntu в sView, т.к. при выпуске нового релиза пакет с исходным кодом sView закидывается в Launchpad для всех активных в нём Ubuntu, и таким образом проверяется компилябельность на разнообразии версий. Launchpad не даёт загружать новые пакеты для старых Ubuntu с какого-то момента, поэтому обычно как только такой момент наступает, то своместимость кода со старыми Ubuntu может быть поломана незаметно.

Ошибка компиляции av_frame_get_side_data скорее всего вызвана патчем
" StVideoQueue::getFrameBuffer() - use sidedata to pass PTS within old sync code"
https://github.com/gkv311/sview/commit/376f2a2d9b6dfee13f75c64b47119d3bcd58cf79
который был сделан для более простой поддержки совместимсти кода с форком LibAV актуальной версии.

Если вы знакомы с git'ом, то можно просто отревертировать данный коммит на текущем мастере и попробовать собрать sView без данного изменения - возможно, это будет последняя проблема сборки:
`git revert 376f2a2d9b6dfee13f75c64b47119d3bcd58cf79 --no-edit`

**Comment by gkv311** [comment]
5808c29943aba39d4a02f4ecea02b6b549ffd02f #
