### ISSUE TITLE
Adjusting output anaglyph colors. Is it possible?

### ISSUE THREAD

**Issue by anatoliis** [gkv311/sview#46]
I have a problem with red color, it doesn't fit my glasses, so I see two pictures at a time. Is it possible to adjust colors? Or maybe I can recompile application with changes to some values?

**Comment by gkv311** [comment]
There is no interface for calibration of Anaglyph output - only the list of standard R/G/B combinations with several sub-options.

You can play with Anaglyph GLSL programs in **shaders/StOutAnaglyph/** folder within installation folder or source code - they should be loaded during application start if I recall correctly.
- fAnaglyphSimple.shf corresponds to "Simple".
- fAnaglyphOptim.shf corresponds to "Optimized".
Have no idea though if it is possible calibrating filters to solve the problem.

Basic idea of Anaglyph glasses is that they should match RGB triad on LCD monitor.
Probably color profile selected in Monitor or in system setting may affect - try disabling "beautifiers" like cinema/game profile in monitor / select sRGB color profile if monitor supports extended profile.
