### ISSUE TITLE
Wish: 16 bit image support (TIFF, PNG) 

### ISSUE THREAD

**Issue by Micha-Pano** [gkv311/sview#57]
Could be implemented to open 16bit images please? For example at the
moment I miss to open 16 bit TIF files, but also PNG could be great.

Example: I use a panorama camera and my images are in 16bit TIFF format, some times PNG. I miss to open this images per sView.

Best -
Micha

**Comment by Micha-Pano** [comment]
... and maybe it could recognized that images are some times sRGB and some times linear RGB. But at first a standard sRGB support would be fine.

**Comment by gkv311** [comment]
Could you please attach some sample files to this issue and clarify what kind of problem you actually experience (file is not opened, quality of image is lost, image looks not as expected - in this case some screenshots with expected and actual results would be nice, etc.)?

**Comment by Micha-Pano** [comment]
I saved a downsized pano as example and tested it now - I' surprised to see the downsized TIF works, so it's not a 16bit problem. I saved the pano to 12000x6000 and the sView screen stays black. At full 16384x8192 I get the error message - "Can not load image file: "..." AVCodec library, input file is not an image". The same sized pano as JPG works. 

Since the original TIF is 600MB I uploaded a downsized version of the image. If I take this image and upscale it to 16000x8000 than I get the error message. I think, you could get the error message too, if you upscale it at your side before opening per sView.

[2019-12-09_15-09-23-HDR-small.zip](https://github.com/gkv311/sview/files/3960261/2019-12-09_15-09-23-HDR-small.zip)

**Comment by gkv311** [comment]
Could you please comment which program do you use for upscaling? Probably sharing an original image would be simpler...

**Comment by Micha-Pano** [comment]
Photoshop CS4. But the original image was saved per Affinity. Both can't be opened. If the upscaled version doesn't show the error than I could try to send you the original image too.

**Comment by gkv311** [comment]
I don't have Photoshop. I've saved upscaled TIFF image via GIMP, and it is opened file, but image format settings (apart from resolution) are most likely different.

**Comment by Micha-Pano** [comment]
An upload of the original image per wetransfer is running and needs approx. 1 hour.

**Comment by gkv311** [comment]
Could you please comment which platform and sView version you are using? And probably also which graphics card.


![sview_pano_tiff](https://user-images.githubusercontent.com/851453/70803656-a0195900-1dc5-11ea-8d04-e7771f69d356.jpg)

**Comment by Micha-Pano** [comment]
I use Win10 64 and sView build 2019-8-28 and my system card is a 1080ti plus 2x2080ti. The Nvida settings say, OpenGL "automatic", so I suppose so one of the 2080ti is used.


![Screen-Shot 533](https://user-images.githubusercontent.com/58846634/70805389-19f71580-1db9-11ea-8545-f90d2dbbc13a.PNG)

**Comment by gkv311** [comment]
You are using 32-bit version of sView, why?
This is the origin of the problem - image file is too big to be loaded into 32-bit address space (possibly with converted copy).

**Comment by Micha-Pano** [comment]
I have seen only one installation file at the web side and if I start it, than I get the 32bit version. 
http://www.sview.ru/en/download/

What can I do to install the 64bit version?

**Comment by gkv311** [comment]
Installation file contains both 32-bit (for compatibility with old 32-bit browsers) and 64-bit versions.
How do you start sView?

**Comment by Micha-Pano** [comment]
I got it - I use the image browser XnView where I set a shortcut to open panoramas per XnView. I have overseen there that there is an extra 64bit version in a subfolder. Thank you for your patient to figure out the issue. It works perfect now.

**Comment by gkv311** [comment]
So I suppose the issue could be closed.
