### ISSUE TITLE
Subtitles do not display properly

### ISSUE THREAD

**Issue by jclement46** [gkv311/sview#58]
I have a video with subtitles that displays the subtitles twice on the left and right of the movie.  This happens both for the Android and Windows version.  In the windows version I set DVDsub, and it is also set for bottom.  It also does this for above.  I have enclosed a screenshot of the video.  I have looked at the video using other non 3D players and they just show the SBS anamorphic image with just one copy of the subtitle.

According to Kiril:
What sView currently expects is monoscopic subtitles (so that subtitles of normal 2D version of the film can be correctly displayed).
So that extra option will be necessary to be implemented (another behaviour cannot be just forced).
Although personally I prefer text-based subtitles anyway, as they are more predictable.
---------------------
The subtitles were encoded by DVDFab so I have little control over them.  I have included a screenshot of the problem.

![Screenshot of subtitled video sView](https://user-images.githubusercontent.com/58582719/70828558-31ca9b80-1db1-11ea-959c-46a1f1172b5c.jpg)

**Comment by gkv311** [comment]
Could you please share some file sample(s)?

**Comment by jclement46** [comment]
Here is some information about the video.  I can't seem to excerpt just a small sample as it is ripped as a side by side video from a 3D Blu-Ray, and the ripping program does not have the capability of just ripping a small section..  I am including an image from a regular non 3D player and the metadata.  It would seem that the ripper created a copy of the subtitles over both L & R images.  This will reproduce them properly if the SBS image is transmitted to a device which then decodes it separately.

![Subtitles in VLC player](https://user-images.githubusercontent.com/58582719/72084691-9225fd80-32c9-11ea-9f81-e76ee507ef45.jpg)
[General Movie tags.txt](https://github.com/gkv311/sview/files/4041387/General.Movie.tags.txt)

**Comment by gkv311** [comment]
Without a sample it is difficult to determine how image-based subtitles encode stereo-pair (do they have width of original video or clipped?).

**Comment by gkv311** [comment]
A blind fix has been pushed to master.

**Comment by gkv311** [comment]
Subtitles are not displayed correctly with provided SbS sample.
In addition, image-based subtitles are now scaled by Font Size parameter, pgssub are scaled down by 0.5x factor, and also scaled by DPI factor. So that their behavior is now closer to text-based subtitles.

O/U is also handled by the code, but not tested (no sample). The sample has 1:1 PAR, so in case of DVD sample, there might be mapping issues (also sample is needed for checking). But probably such files do not exist anyway.

**Comment by jclement46** [comment]
This is actually not a comment.  The display of slides and videos reverse the R/L images on autostereoscopic tablet or phone displays when switching between slides and videos.  As a result, if Videos can be viewed straight on slides have to be viewed at an angle.  This is an issue that should be fixed, but it does not a major problem.  If slides and videos are intermixed it will be a big nuisance to have to readjust the angle of the display when switching from one to the other.

 

I have verified it on my 3 currently used devices, so it is not device dependent.

 

Regards,

John
