### ISSUE TITLE
Hiding interface when swiping through pictures

### ISSUE THREAD

**Issue by volute91** [gkv311/sview#61]
Currently, the interface buttons and menu appear as soon as the screen is touched. This is inconvenient when swiping between pictures or pinch-zooming a picture. Is it possible to prevent the interface from appearing when performing these actions? I.e. make the interface appear only when the screen is touched briefly but not when it is swiped or pinch-zoomed.

**Comment by gkv311** [comment]
Touchscreen gestures behavior has been changed to:
- Single tap reveals UI.
- Double tap does not reveal UI.
- Moving touches (panning / zooming / swiping) do not reveal UI.
