### ISSUE TITLE
binary-or-shlib-calls-gethostbyname

### ISSUE THREAD

**Issue by awissu** [gkv311/sview#7]
Hello!
I to build package (sview-14_01) and OBS output gave me the following warning:
[  748s] sview.x86_64: W: missing-call-to-setgroups-before-setuid /usr/lib64/sView/libStMoviePlayer.so
[  748s] This executable is calling setuid and setgid without setgroups or initgroups.
[  748s] There is a high probability this mean it didn't relinquish all groups, and
[  748s] this would be a potential security issue to be fixed. Seek POS36-C on the web
[  748s] for details about the problem.
....
[  748s] sview.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/sView/libStShared.so
[  748s] sview.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/sView/libStMoviePlayer.so
[  748s] The binary calls gethostbyname(). Please port the code to use getaddrinfo().

Thank you for the attention, hope this report helps development.

**Comment by gkv311** [comment]
Hi, thank you for reporting!

Both issues are related to mongoose web-server which can be used by sView for simple remote control (you can disable it by resetting HAVE_MONGOOSE in Makefile):
https://github.com/cesanta/mongoose

I'll try to provide fixes though I'm not very familiar with networking.

**Comment by gkv311** [comment]
I just have removed unused functions, so there should not be any warnings now.
