### ISSUE TITLE
Use volume button to change pictures in Android

### ISSUE THREAD

**Issue by jclement46** [gkv311/sview#72]
This enhancement was created a number of years ago, but it has been dropped.  I find the swiping is unreliable, but the volume buttons worked well.  This is available in 3DSteroid and some other 3D viewers.  So please put the code back in for this.  The old code still works on a 3D phone that I have not updated.

**Comment by gkv311** [comment]
This feature is still there.
I believe that you are talking about "Mix images & videos".
These buttons cannot be overloaded in video player, as they are the only way to manage audio, and changing behavior for images / videos for them within the same playlist would be unexpected.

**Comment by jclement46** [comment]
Actually this is just for pictures.  So when viewing a picture, the volume control can go to the next one. but obviously this should not be done for videos.  The volume doesn't switch picturex if videos and mixed are deselected, but in that case it should be OK to do this.  Sometimes there is no substitute for a physical control such as a button or knob instead of touch or voice controls.  Toyota made a big mistake when they omitted the volume control on their fancy automobile touch screen.  I wonder if it is possible to add a couple of small remote physical buttons to the phone.  I suppose gamers have something that might be usable.
