### ISSUE TITLE
Text not displaying properly

### ISSUE THREAD

**Issue by awissu** [gkv311/sview#8]
Hello again!
More information: 
System: openSUSE 13.2/13.1 KDE 4.14.6
The list of dependencies to install package: https://pmbs.links2linux.de/package/binary/home:awissu/sview?arch=x86_64&filename=sview-14.01-2.1.x86_64.rpm&repository=openSUSE_13.2

Screenshot: http://paste.opensuse.org/86326729

List information about the files:
ls /usr/share/fonts/truetype/{DejaVu*,FreeS*}
/usr/share/fonts/truetype/DejaVuSans-BoldOblique.ttf
/usr/share/fonts/truetype/DejaVuSans-Bold.ttf
/usr/share/fonts/truetype/DejaVuSansCondensed-BoldOblique.ttf
/usr/share/fonts/truetype/DejaVuSansCondensed-Bold.ttf
/usr/share/fonts/truetype/DejaVuSansCondensed-Oblique.ttf
/usr/share/fonts/truetype/DejaVuSansCondensed.ttf
/usr/share/fonts/truetype/DejaVuSans-ExtraLight.ttf
/usr/share/fonts/truetype/DejaVuSansMono-BoldOblique.ttf
/usr/share/fonts/truetype/DejaVuSansMono-Bold.ttf
/usr/share/fonts/truetype/DejaVuSansMono-Oblique.ttf
/usr/share/fonts/truetype/DejaVuSansMono.ttf
/usr/share/fonts/truetype/DejaVuSans-Oblique.ttf
/usr/share/fonts/truetype/DejaVuSans.ttf
/usr/share/fonts/truetype/DejaVuSerif-BoldItalic.ttf
/usr/share/fonts/truetype/DejaVuSerif-Bold.ttf
/usr/share/fonts/truetype/DejaVuSerifCondensed-BoldItalic.ttf
/usr/share/fonts/truetype/DejaVuSerifCondensed-Bold.ttf
/usr/share/fonts/truetype/DejaVuSerifCondensed-Italic.ttf
/usr/share/fonts/truetype/DejaVuSerifCondensed.ttf
/usr/share/fonts/truetype/DejaVuSerif-Italic.ttf
/usr/share/fonts/truetype/DejaVuSerif.ttf
/usr/share/fonts/truetype/FreeSansBoldOblique.ttf
/usr/share/fonts/truetype/FreeSansBold.ttf
/usr/share/fonts/truetype/FreeSansOblique.ttf
/usr/share/fonts/truetype/FreeSans.ttf
/usr/share/fonts/truetype/FreeSerifBoldItalic.ttf
/usr/share/fonts/truetype/FreeSerifBold.ttf
/usr/share/fonts/truetype/FreeSerifItalic.ttf
/usr/share/fonts/truetype/FreeSerif.ttf

**Comment by gkv311** [comment]
Hi,

what GPU and drivers are in use?

**Comment by awissu** [comment]
glxinfo|egrep 'OpenGL|^direct' 
direct rendering: Yes
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce 9500 GT/PCIe/SSE2
OpenGL core profile version string: 3.3.0 NVIDIA 340.76
OpenGL core profile shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.3.0 NVIDIA 340.76
OpenGL shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 NVIDIA 340.76 340.76
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.00
OpenGL ES profile extensions:

**Comment by awissu** [comment]
[Fixed] Use sview >= 15.08
