### ISSUE TITLE
DTS and AC-3 pass-through

### ISSUE THREAD

**Issue by hugo-lyppens** [gkv311/sview#82]
I would like to be able to pass via bitstreaming DTS or AC-3 to my receiver connected via digital output. At the moment I cannot choose any other output than OpenAL.

If this can be done on Windows via registry values under Computer\HKEY_CURRENT_USER\Software\sView\StMoviePlayer
please let me know.

**Comment by gkv311** [comment]
sView supports only [OpenAL soft](https://openal-soft.org/) library for Audio playback.
So far, there are no extensions for passing through encoded DTS/AC-3 stream via OpenAL to digital receivers supporting these codecs natively.

You can choose *Audio Device* from OpenAL list within sView - it might contain devices like "S/PDIF", and you may also configure multi-channel output within OpenAL soft. But in any case, player will first decode Audio stream via FFmpeg library, and then pass it to OpenAL.
