### ISSUE TITLE
WEBP alpha channel not well handled

### ISSUE THREAD

**Issue by JackDesBwa** [gkv311/sview#83]
**Issue:** sView supports WEBP format, but some images with alpha channel are not handled correctly.

**Observed with:** sView 19.10 x86_64 / GL: Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2), 3.0 Mesa 19.3.4
**Remark:** It looks almost correct (blocky on semi-transparent parts) with some images, but it might be because some software encode black color behind the transparent parts of the image.

**Exemple:**
Here is an image that exhibit the behavior: [giraffe.webp.gz](https://github.com/gkv311/sview/files/4397876/giraffe.webp.gz). It is gziped because otherwise github do not want to attach it in the issue. This image was encoded by Firefox when I saved it and its encoder set non-black zones behind the transparent parts.
Expected result: https://stereopix.net/photo:koUNdj7HgW/ (Correct in Firefox 74 for example).
Visual comparison, parallel mode:
![giraffe_screenshot](https://user-images.githubusercontent.com/493717/77834184-00e55b00-7143-11ea-933d-030ceb4db6f8.jpg)

**Comment by gkv311** [comment]
[giraffe.webp.gz](https://github.com/gkv311/sview/files/4398396/giraffe.webp.gz)

**Comment by gkv311** [comment]
Which version of Linux is used?
![image](https://user-images.githubusercontent.com/851453/77843318-8b11db80-71a4-11ea-96fd-0a65796cc2ab.png)

**Comment by JackDesBwa** [comment]
I am using Archlinux. I thought sview was in official repos, but apparently I compiled it some time ago, probably with this unofficial recipe: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sview
On the system, libwebp is at version 1.1.0

I am pretty confused by the versions.
Last version is said to be:
17.04: Github Releases, git tags, website for Linux sources & Mac
19.08: Website for Linux via PPA
20.01: Website for Windows & Android

Based on the sha of the downloaded sources, my version is apparently from the Aug 4, 2019.
Do you advice to compile another version?

**Comment by gkv311** [comment]
The image has yuva420p pixel format, which has been converted by FFmpeg to RGB24 as fallback approach in sView. So that image you see is the result of FFmpeg conversion, which can be reproduced like this:
```
> ffmpeg -i giraffe.webp giraffe.jpg
```
The artifacts are either stored within original file itself within transparent pixels, or might be caused by encoding algorithm considering transparent pixels may define undefined RGB / YUV values as they are invisible by alpha mask.

I have pushed the patch which introduces support of yuva (yuv + alpha) formats in sView, so that they are handled now in the same way as rgba files.

**Comment by gkv311** [comment]
> Do you advice to compile another version?

You can try building sView from current master branch (clone this git repository).

**Comment by JackDesBwa** [comment]
I was about to say that it did not work, but I saw that the project is separated into multiple dynamic libraries and that in my first test the system ones were loaded.
By ensuring that I load the new ones... **it works**. Nice and fast fix!
