### ISSUE TITLE
Ubuntu 20.04 install

### ISSUE THREAD

**Issue by freewee** [gkv311/sview#87]
Hi Kirill 
Needing to install SView on a fresh version of Ubuntu (20.04 LTS), I have the same problem as I had when upgrading from the 16.04 to the 18.04: sview has the same name of a packet installed by default, so I can' t install SView stereoscopic...
Is there something to do???
Thank you for your work!
Dominique Breton

**Comment by gkv311** [comment]
Are you trying to install pre-built binaries from [Launchpad](https://launchpad.net/~sview/+archive/ubuntu/stable)? Then there were just no packages from Ubuntu 20.04 uploaded.

I've just pushed it - you may check.
