### ISSUE TITLE
how to use VS 2015 with this project?

### ISSUE THREAD

**Issue by RYG81** [gkv311/sview#9]
Is there any guide on using this on windows with Visual Studio 2015.
I really want to build it.

**Comment by gkv311** [comment]
Hello,

sView comes with project files for VS2010 (see solution sView.sln at the root of the repository).
VS2015 should be able to upgrade them, though I have not tried this yet.

You will need also to build dependencies (FFmpeg, FreeType,...) following their instructions.

**Comment by RYG81** [comment]
Thanks, I will try for that?
Also could you help me on how can I modify the user interface part? Which file to change for the interface / UI?

**Comment by gkv311** [comment]
The root of user interface logic is located in StImageViewer/StImageViewerGUI.cpp for image viewer and StMoviePlayer/StMoviePlayerGUI.cpp for Media Player

**Comment by RYG81** [comment]
Thank you very much. I will look in to it. Also is it possible to use your project with QT Editor?

**Comment by gkv311** [comment]
I have checked VS2015 and it converted VS2010 projects and compiled sView without issues.

> Also is it possible to use your project with QT Editor?

If you are asking about Qt Creator then there are no .pro files available for them.
Please refer to its documentation if Qt Creator is able to import projects from other IDEs (Code::Blocks has such functionality, for example).
